secret_name: app-one-test
key_config:
  DB_HOST:
    path: config/app-one/dev
    key: DB_HOST
  DB_USER:
    path: users/{{DEV_NAME}}/db/somedb/dev
    key: username
  DB_PASS:
    path: users/{{DEV_NAME}}/db/somedb/dev
    key: password
  A_KEY_OF_A_ANOTHER_THING:
    path: config/app-one/dev
    key: A_KEY_OF_A_ANOTHER_THING
  ENV:
    path: config/app-one/dev
    key: ENV
  PAYMENT_EMAIL_QUEUE_NAME:
    path: config/app-one/dev
    key: PAYMENT_EMAIL_QUEUE_NAME
  RABBITMQ_CONNECTION_NAME:
    path: config/app-one/dev
    key: RABBITMQ_CONNECTION_NAME
  RABBITMQ_HOST:
    path: config/app-one/dev
    key: RABBITMQ_HOST
  RABBITMQ_USER:
    path: secrets/rabbitmq/dev/app-one
    key: username
  RABBITMQ_PASS:
    path: secrets/rabbitmq/dev/app-one
    key: password
